### ISSUE TITLE
Bug on the installation 

### ISSUE THREAD

**Issue by pgervaix** [sciencegalleryderek/com.sciencegallery.mailchimp#12]
Hi, 
I use civicrm 4.3.6 with drupal , i have a DB Error: constraint violation during the installation (see below

Thanks in advance
//
Oct 15 11:34:43  [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

```
[code] => -3
[message] => DB Error: constraint violation
[mode] => 16
[debug_info] => INSERT INTO civicrm_navigation (domain_id , label , name , url , permission , parent_id , is_active , has_separator , weight ) VALUES ( 1 , 'MailChimp Settings' , 'MailChimp Settings' , 'civicrm/admin/setting/mailchimp' , 'access CiviCRM' ,  137 ,  1 ,  0 ,  1 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`civiihr5bc3`.`civicrm_navigation`, CONSTRAINT `FK_civicrm_navigation_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `civicrm_navigation` (`id`) ON DELETE CASCADE)]
[type] => DB_Error
[user_info] => INSERT INTO civicrm_navigation (domain_id , label , name , url , permission , parent_id , is_active , has_separator , weight ) VALUES ( 1 , 'MailChimp Settings' , 'MailChimp Settings' , 'civicrm/admin/setting/mailchimp' , 'access CiviCRM' ,  137 ,  1 ,  0 ,  1 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`civiihr5bc3`.`civicrm_navigation`, CONSTRAINT `FK_civicrm_navigation_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `civicrm_navigation` (`id`) ON DELETE CASCADE)]
[to_string] => [db_error: message="DB Error: constraint violation" code=-3 mode=callback callback=CRM_Core_Error::handle prefix="" info="INSERT INTO civicrm_navigation (domain_id , label , name , url , permission , parent_id , is_active , has_separator , weight ) VALUES ( 1 , 'MailChimp Settings' , 'MailChimp Settings' , 'civicrm/admin/setting/mailchimp' , 'access CiviCRM' ,  137 ,  1 ,  0 ,  1 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`civiihr5bc3`.`civicrm_navigation`, CONSTRAINT `FK_civicrm_navigation_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `civicrm_navigation` (`id`) ON DELETE CASCADE)]"]
```

)

Oct 15 11:34:43  [info] $backTrace = #0 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Error.php(196): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /var/www/siteprod/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /var/www/siteprod/sites/all/modules/civicrm/packages/DB.php(969): PEAR_Error->PEAR_Error("DB Error: constraint violation", -3, 16, (Array:2), "INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...")
#4 /var/www/siteprod/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-3, 16, (Array:2), "INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...")
#5 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -3, NULL, NULL, "INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...", "DB_Error", TRUE)
#6 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/mysql.php(898): DB_common->raiseError(-3, NULL, NULL, NULL, "1452 *\* Cannot add or update a child row: a foreign key constraint fails (`ci...")
#7 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/mysql.php(327): DB_mysql->mysqlRaiseError()
#8 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...")
#9 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/DataObject.php(2421): DB_common->query("INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...")
#10 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/DataObject.php(1055): DB_DataObject->_query("INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...")
#11 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/DAO.php(287): DB_DataObject->insert()
#12 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/BAO/Navigation.php(117): CRM_Core_DAO->save()
#13 /var/www/siteprod/sites/default/files/civicrm/extensions/com.sciencegallery.mailchimp-1.2/mailchimp.php(425): CRM_Core_BAO_Navigation::add((Array:8))
#14 /var/www/siteprod/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(60): mailchimp_civicrm_enable()
#15 /var/www/siteprod/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(45): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), "enable")
#16 /var/www/siteprod/sites/all/modules/civicrm/CRM/Extension/Manager.php(219): CRM_Extension_Manager_Module->onPreInstall(Object(CRM_Extension_Info))
#17 /var/www/siteprod/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(188): CRM_Extension_Manager->install((Array:1))
#18 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Form.php(246): CRM_Admin_Form_Extensions->postProcess()
#19 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#20 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(60): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#21 /var/www/siteprod/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#22 /var/www/siteprod/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#23 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Controller.php(316): HTML_QuickForm_Page->handle("next")
#24 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(374): CRM_Core_Controller->run()
#25 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(178): CRM_Core_Page_Basic->edit(1, NULL)
#26 /var/www/siteprod/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(127): CRM_Core_Page_Basic->run()
#27 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Invoke.php(292): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#28 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Invoke.php(70): CRM_Core_Invoke::runItem((Array:13))
#29 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#30 /var/www/siteprod/sites/all/modules/civicrm/drupal/civicrm.module(436): CRM_Core_Invoke::invoke((Array:3))
#31 [internal function](): civicrm_invoke("admin", "extensions")
#32 /var/www/siteprod/includes/menu.inc(517): call_user_func_array("civicrm_invoke", (Array:2))
#33 /var/www/siteprod/index.php(21): menu_execute_active_handler()
#34 {main}

//
The drupal Log:

$backTrace = #0 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Error.php(196): CRM_Core_Error::backtrace("backTrace", TRUE) #1 [internal function](): CRM_Core_Error::handle(Object(DB_Error)) #2 /var/www/siteprod/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error)) #3 /var/www/siteprod/sites/all/modules/civicrm/packages/DB.php(969): PEAR_Error->PEAR_Error("DB Error: constraint violation", -3, 16, (Array:2), "INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...") #4 /var/www/siteprod/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-3, 16, (Array:2), "INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...") #5 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -3, NULL, NULL, "INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...", "DB_Error", TRUE) #6 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/mysql.php(898): DB_common->raiseError(-3, NULL, NULL, NULL, "1452 *\* Cannot add or update a child row: a foreign key constraint fails (`ci...") #7 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/mysql.php(327): DB_mysql->mysqlRaiseError() #8 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...") #9 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/DataObject.php(2421): DB_common->query("INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...") #10 /var/www/siteprod/sites/all/modules/civicrm/packages/DB/DataObject.php(1055): DB_DataObject->_query("INSERT INTO civicrm_navigation (domain_id , label , name , url , permission ,...") #11 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/DAO.php(287): DB_DataObject->insert() #12 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/BAO/Navigation.php(117): CRM_Core_DAO->save() #13 /var/www/siteprod/sites/default/files/civicrm/extensions/com.sciencegallery.mailchimp-1.2/mailchimp.php(425): CRM_Core_BAO_Navigation::add((Array:8)) #14 /var/www/siteprod/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(60): mailchimp_civicrm_enable() #15 /var/www/siteprod/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(45): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), "enable") #16 /var/www/siteprod/sites/all/modules/civicrm/CRM/Extension/Manager.php(219): CRM_Extension_Manager_Module->onPreInstall(Object(CRM_Extension_Info)) #17 /var/www/siteprod/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(188): CRM_Extension_Manager->install((Array:1)) #18 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Form.php(246): CRM_Admin_Form_Extensions->postProcess() #19 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess() #20 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(60): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next") #21 /var/www/siteprod/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next") #22 /var/www/siteprod/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next") #23 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Controller.php(316): HTML_QuickForm_Page->handle("next") #24 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(374): CRM_Core_Controller->run() #25 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(178): CRM_Core_Page_Basic->edit(1, NULL) #26 /var/www/siteprod/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(127): CRM_Core_Page_Basic->run() #27 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Invoke.php(292): CRM_Admin_Page_Extensions->run((Array:3), NULL) #28 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Invoke.php(70): CRM_Core_Invoke::runItem((Array:13)) #29 /var/www/siteprod/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3)) #30 /var/www/siteprod/sites/all/modules/civicrm/drupal/civicrm.module(436): CRM_Core_Invoke::invoke((Array:3)) #31 [internal function](): civicrm_invoke("admin", "extensions") #32 /var/www/siteprod/includes/menu.inc(517): call_user_func_array("civicrm_invoke", (Array:2)) #33 /var/www/siteprod/index.php(21): menu_execute_active_handler() #34 {main}

**Comment by pgervaix** [comment]
Hi I have change the Parent_ID for 137 (doesn't exist) for 90 (ID of administer CRM)
and thats will work well
