### ISSUE TITLE
Failed To Claim Next Task

### ISSUE THREAD

**Issue by davidschenz** [sciencegalleryderek/com.sciencegallery.mailchimp#25]
Hello -

First, I wanted to thank you for creating this module. I'm running CiviCRM 4.4.4 on top of Drupal 7.14. I'm having a spot of trouble. We setup a mail chimp account, configured an api key, added the api key into the MailChimp config in Civi and then ran the sync job. For some reason, I'm getting the error message "Failed to claim next task" when running the sync. Below is the output in the Civi log. Would you have any suggestion on what might be causing this issue or how to go about debugging it?

Thanks for the help
David

```
Mar 30 13:28:17  [info] $no items found is not set

Mar 30 13:28:17  [info] $CRM_Queue_Page_AJAX_runNext_error = Exception: "Failed to claim next task"
#0 /etc/drupal/7/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(44): CRM_Queue_Runner->runNext(TRUE)
#1 /etc/drupal/7/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(80): CRM_Queue_Page_AJAX::{closure}()
#2 /etc/drupal/7/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(47): CRM_Queue_ErrorPolicy->call(Object(Closure))
#3 [internal function](): CRM_Queue_Page_AJAX::runNext((Array:4))
#4 /etc/drupal/7/sites/all/modules/civicrm/CRM/Core/Invoke.php(289): call_user_func((Array:2), (Array:4))
#5 /etc/drupal/7/sites/all/modules/civicrm/CRM/Core/Invoke.php(72): CRM_Core_Invoke::runItem((Array:13))
#6 /etc/drupal/7/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#7 /etc/drupal/7/sites/all/modules/civicrm/drupal/civicrm.module(456): CRM_Core_Invoke::invoke((Array:4))
#8 [internal function](): civicrm_invoke("queue", "ajax", "runNext")
#9 /usr/share/drupal7/includes/menu.inc(516): call_user_func_array("civicrm_invoke", (Array:3))
#10 /usr/share/drupal7/index.php(21): menu_execute_active_handler()
#11 {main}
```

**Comment by peoute** [comment]
David, I experienced the same error on a fresh install of CiviCRM 4.4.4 on Wordpress 3.8.1.

The extension lists compatibility with CiviCRM 4.3. I wonder if 4.4.x broke something. . .

There is some discussion about this a couple months ago, though, on issue https://github.com/sciencegalleryderek/com.sciencegallery.mailchimp/issues/18

FWIW

**Comment by sciencegalleryderek** [comment]
Hi David,

Yes - this appears in 4.4.4, smart group sync still works though

D

**Comment by vishram74** [comment]
So does this mean that we can ignore the error message and the sync will still work?
